name: sangt6_nhom6_chamcong_nv
description: "Ứng dụng Flutter demo chấm công NFC kết nối backend."
publish_to: "none"

# Phiên bản ứng dụng
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"   # Dart SDK
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- Gói chính cho NFC + HTTP ---
  nfc_manager: ^3.3.0
  http: ^1.5.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  jwt_decode: ^0.3.1
  provider: ^6.1.2
  excel: ^2.1.0
  path_provider: ^2.1.3
  share_plus: ^7.2.1
  # (tùy chọn cho các bước sau)
  # camera: ^0.10.6
  # local_auth: ^2.3.0
  # path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
